sudo: false
language: python
cache: pip
env:
  - AWS_DEFAULT_REGION=eu-west-1
install:
  - apt-get install nodejs
  - npm install -g aws-cdk
  - pip install -r requirements/all.txt
script:
  - pytest --cov=source test/unit
  - invoke package
  - invoke deploy
  - pytest test/component
after_success:
  - codecov